### ISSUE TITLE
Error from Genymotion

### ISSUE THREAD

**Issue by standfv** [TakuSemba/RtmpPublisher#9]
:app:transfromNativeLibsWithStripDebugSymbolForDebug

**Comment by justin-vanwinkle** [comment]
This is an issue involving NDK 17.  If you remove it from the tools, you'll be able to successfully build.

When you submit issues, please give additional relevant information that can assist someone in recreating your issue.  Otherwise, you will have difficulty getting answers -- and the answers that you do get will likely not be relevant.

**Comment by TakuSemba** [comment]
@justin-vanwinkle thank you for the comment. 

@standfv 
im closing this issue. please reopen this if you need more help
